DOMAIN = "revogi"

ATTR_LEVEL = "water_level"
ATTR_TDS   = "water_tds"
ATTR_LED   = "led"
ATTR_LEDMODE = "ledmode"
ATTR_SWITCH = "switch"
ATTR_FILTERTIME = "filtertime"
ATTR_MOTORTIME = "motortime"
ATTR_WATERTIME = "watertime"
ATTR_ALARM = "consumables_alert"
CONF_SERIAL = "serial"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
DEFAULT_NAME = "Petoneer Revogi"
