DOMAIN = "revogi"

ATTR_LEVEL = "water_level"
ATTR_TDS   = "water_tds"
ATTR_LED   = "led"
ATTR_LEDMODE = "ledmode"
ATTR_SWITCH = "switch"
CONF_SERIAL = "serial"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
DEFAULT_NAME = "Petoneer Revogi"
